config/routes.rb
Syn::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signup',    to:   'users#new',              via: 'get'
  match '/signin',    to:   'sessions#new',           via: 'get'
  match '/signout',   to:   'sessions#destroy',       via: 'delete'
  match '/contact',   to:   'static_pages#contact',   via: 'get'
  match '/holocaust_memorial',   to:   'reports#holocaust_memorial',   via: 'get'
  match '/yizkor_book',          to:   'reports#yizkor_book',          via: 'get'

  resources :accounts do
    resources :people
    resources :mentions
    resources :relationships
  end

  resources :people do
    resources :mentions
    resources :relationships
  end

  

end

app/models/account.rb
class Account < ActiveRecord::Base
	acts_as_paranoid

	has_one	 :address, dependent: :destroy
	has_many :payments, dependent: :destroy
	has_many :mentions, as: :mentionable, dependent: :destroy

	has_many :relationships
	has_many :sponsors, -> { uniq }, through: :relationships
	has_many :yizkors, -> { uniq }, through: :relationships

	has_many :people, dependent: :destroy
	# has_many :yizkors, -> { uniq }, through: :sponsors
	# has_many :relationships, through: :people
	# has_many :yizkors, -> { uniq }, through: :people

	accepts_nested_attributes_for :address
	accepts_nested_attributes_for :relationships
	# accepts_nested_attributes_for :sponsors
	# accepts_nested_attributes_for :yizkors
	accepts_nested_attributes_for :people, allow_destroy: true
	accepts_nested_attributes_for :mentions, allow_destroy: true

	validates :tag, presence: true, uniqueness: { case_sensitive: false, scope: [:deleted_at] }
	validates :name, presence: true


	def publication_history
		history = ""
		book_years = self.mentions.pluck(:year).uniq
		
		history << "Account #{self.tag}::#{self.name} mentioned in: #{book_years.to_s}"
		self.people.each do |person|
			person_full_name = "#{person.first_name} #{person.last_name}"
			holocaust_years = person.mentions.pluck(:year).uniq
			person_report = "#{person_full_name} mentioned in: #{holocaust_years.to_s}"
			history << person_report
		end

		history
	end

	# TODO: improve search to disregard case and to search associated records
	def Account.search(search)
	  if search
	    where("tag LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%") 
	  else
	    all
	  end
	end

	def mentioned_in?(year) 
		mentions.map(&:years).include?(year)
	end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	def index
		@accounts = Account.search(params[:search])
	end

  def new
  	@account = Account.new
  end

  def show
  	@account = Account.find params[:id]
  end

  def edit
  	@account = Account.find params[:id]
  end

  def update
  	@account = Account.find params[:id]

    # binding.pry
    # render 'edit'

    if @account.update_attributes(account_params)
      # update is good (note: use account_params to avoid malicious passing of other params)
      flash[:success] = "Changes saved.  Hope you like it this way better."
      # redirect_to account_path
      redirect_to edit_account_path
    else
      flash.now[:error] = "Changes not saved.  Look for errors below (or check logs).  Logs say:" + @account.errors.messages.inspect
      # Rails.logger.info(@account.errors.messages.inspect)
      render 'edit'
    end

  end

# !PRIVATE! 
  private

    def account_params
    	params.require(:account).permit(:tag, :name, 
                                      address_attributes: 
                                      [:id, :label, :street1, :street2, :city, :state, :zip],
                                      mentions_attributes: 
                                      [:id, :year, :mentionable_id, :mentionable_type, :source, :_destroy],
                                      people_attributes:
                                      [:id, :first_name, :last_name, :sort_order, :_destroy])
    end

end

                                      # people_attributes:
                                      # [:id, :first_name, :last_name, :sort_order, :_destroy],
                                      # sponsors_attributes:
                                      # [:id, :first_name, :last_name, :sort_order],

app/helpers/accounts_helper.rb
module AccountsHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      # render(association.to_s.singularize + "_fields", f: builder)
      render("person_fields", f: builder)
    end
    link_to(name, '#', class: "btn add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/accounts/_account.OLD.html.erb
<li>

	<%= content_tag(:span, account.name.gsub('~',' '), class: "name") %>
	<%= content_tag(:span, "{ " + 	account.tag + " }", class: "pull-right text-right") %>
	<%= content_tag(:br) %>


	<ol class="yizkors">
		<% if account.yizkors.count > 0 %>
			<%= render partial: 'person', collection: account.yizkors.order(:sort_order) %>
		<% else %>
			<%= "No yizkors." %>
		<% end %>
	</ol>

	<ul class="holocaust">
		<li class="<%= account.mentioned_in?(Date.current.year) ? 'mentioned':'not-mentioned' %>">
				<%= "Holocaust memorial" %>
				<span class="<%= account.mentioned_in?(1.year.ago.year) ? 'mentioned':'not-mentioned' %>">
						<%= "(#{1.year.ago.year}: Holocaust memorial)" %>
				</span>
		</li>
	</ul>

	<div class="address">
		<% if account.address %>
			<%= render 'accounts/address', address: account.address %>
		<% else %>
			<%= "No mailing address." %>
		<% end %>
	</div>

</li>

  <div class="span8">
    <% if @account.people.any? %>
      <h3>People (<%= @account.people.count %>)</h3>
      <ol class="people">
        <%= render partial: 'person', collection: account.people.order(:sort_order) %>
      </ol>
    <% end %>
  </div>

app/views/accounts/_account.html.erb
<li>

	<%= content_tag(:span, account.name.gsub('~',' '), class: "name") %>
	<%= content_tag(:span, "{ " + 	account.tag + " }", class: "pull-right text-right") %>
	<%= content_tag(:br) %>


	<ol class="yizkors">
		<% if account.yizkors.count > 0 %>
			<%= render partial: 'person', collection: account.yizkors.order(:sort_order) %>
		<% else %>
			<%= "No yizkors." %>
		<% end %>
	</ol>

	<ul class="holocaust">
		<li class="<%= account.mentioned_in?(Date.current.year) ? 'mentioned':'not-mentioned' %>">
				<%= "Holocaust memorial" %>
				<span class="<%= account.mentioned_in?(1.year.ago.year) ? 'mentioned':'not-mentioned' %>">
						<%= "(#{1.year.ago.year}: Holocaust memorial)" %>
				</span>
		</li>
	</ul>

	<div class="address">
		<% if account.address %>
			<%= render 'accounts/address', address: account.address %>
		<% else %>
			<%= "No mailing address." %>
		<% end %>
	</div>

</li>

app/views/accounts/_address.html.erb
<%= "#{ address.label } @ #{ address.street1 }" %>
<%= "#{ address.street2 }" unless address.street2.nil? %> 
<%= ", #{ address.city }, #{ address.state }, #{ address.zip }" %> 

app/views/accounts/_address_fields.html.erb
				<%= f.semantic_fields_for :address do |address| %>
					<%= address.inputs :label, 		class: "span6 row" %>
					<%= address.inputs :street1, 	class: "span6 row" %>
					<%= address.inputs :street2, 	class: "span2 row"%>
					<%= address.inputs :city, 		class: "span4 row"%>
					<%= address.inputs :state, 		class: "span2 row"%>
					<%= address.inputs :zip, 			class: "span2 row"%>
				<% end %>

app/views/accounts/_fields.OLD.html.erb
<div class="row-fluid clearfix offset2">	


	<ul class="nav nav-tabs">
		<li class="active"><a href="#">Participation</a></li>
		<li><a href="#">Basic Information</a></li>
		<li><a href="#">Relationships</a> </li>
	</ul>

	<%= render 'shared/error_messages', object: f.object %>

	<fieldset class="account-fields">
		<div class="form-group span9">
			<%= f.label :name %>
			<%= f.text_field :name, autofocus: true %>
		</div>
		<div class="form-group span2 pull-right">
			<%= f.label :tag %>
			<%= f.text_field :tag %>			
		</div>
	</fieldset><!--/.account-fields-->

	<fieldset class="sponsors-fields">	
		<%= f.fields_for :sponsors, @account.sponsors.order(:sort_order, :id) do |person| %>
			<%= render 'person_fields', f: person %>			
		<% end %>
		<%= link_to_add_fields "Add Person", f, :sponsors %>
	</fieldset><!--/.sponsors-fields-->



</div><!--/.row-->

app/views/accounts/_fields.html.erb
<div class="row-fluid clearfix offset2">	


	<ul class="nav nav-tabs">
		<li class="active"><a href="#">Participation</a></li>
		<li><a href="#">Basic Information</a></li>
		<li><a href="#">Relationships</a> </li>
	</ul>

	<%= render 'shared/error_messages', object: f.object %>

	<fieldset class="account-fields">
		<div class="form-group span9">
			<%= f.label :name %>
			<%= f.text_field :name, autofocus: true %>
		</div>
		<div class="form-group span2 pull-right">
			<%= f.label :tag %>
			<%= f.text_field :tag %>			
		</div>
	</fieldset><!--/.account-fields-->

	<fieldset class="sponsors-fields">	
		<%= f.fields_for :sponsors, @account.sponsors.order(:sort_order, :id) do |person| %>
			<%= render 'person_fields', f: person %>			
		<% end %>
		<%= link_to_add_fields "Add Person", f, :sponsors %>
	</fieldset><!--/.sponsors-fields-->



</div><!--/.row-->

app/views/accounts/_mention_fields.html.erb
<fieldset class="control-group">
	<%= "id: #{f.object.id}" %>
	<%= f.inputs :year, 	class: "span2 row" %>
	<%= link_to_remove_association "del", f, class: "btn btn-mini" %>
</fieldset>

app/views/accounts/_person.html.erb
<li class="<%= person.mentioned_in?(Date.current.year) ? 'mentioned' : 'not-mentioned' %>">
	<%= "#{person.first_name} #{person.last_name}" %>
<span class="<%= person.mentioned_in?(1.year.ago.year) ? 'mentioned' : 'not-mentioned' %>">
	<%= "(#{1.year.ago.year}: #{person.first_name} #{person.last_name})" %>
</span>

<%= person.sponsor? ? '<-- *SPONSOR*' : '' %>
<%= "sort order: #{person.sort_order}" %>
<%= "id: #{person.id}" %>

<%= link_to "delete", person, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: person.first_name %>
</li>

app/views/accounts/_person_fields.html.erb
<fieldset class="control-group">
	<%= f.inputs :sort_order, 	class: "span2 row" %>
	<%= f.inputs :first_name, 	class: "span2 row" %>
	<%= f.inputs :last_name, 		class: "span3 row" %>
	<%= link_to_remove_association "del", f, class: "btn btn-mini" %>
</fieldset>

app/views/accounts/edit.OLD.html.erb
<% provide(:title, "Edit account") %>
<h1>Edit account</h1>

<div class="container">

	<%= semantic_form_for @account, html: { class: 'span9 offset1', multipart: true } do |f| %>
		<%= f.inputs name: "Basic properties", id: "basic" do %>
			<%= f.inputs :name, class: "span6" %>
			<%= f.inputs :tag, 	class: "span2" %>

			<%= f.inputs name: "Address", id: "address", class: "control-group controls row-fluid" do %>
				<%= f.semantic_fields_for :address do |address| %>
					<%= address.inputs :label, 		class: "span6 row" %>
					<%= address.inputs :street1, 	class: "span6 row" %>
					<%= address.inputs :street2, 	class: "span2 row"%>
					<%= address.inputs :city, 		class: "span4 row"%>
					<%= address.inputs :state, 		class: "span2 row"%>
					<%= address.inputs :zip, 			class: "span2 row"%>
				<% end %>
			<% end %>

		<% end %>

		<%= f.inputs name: "Yizkors", id: "yizkors", class: "form-group" do %>
			<%= f.semantic_fields_for :yizkors, @account.yizkors.order(:sort_order, :id), 
																									class: "control-group" do |person| %>
				<%= render 'person_fields', f: person %>				
			<% end %>
	    	<div class='links'>
				<%= link_to_add_association "add yizkor", f, :people %>
	    	</div>
		<% end %>

		<%= f.actions class: "control-group controls row-fluid" do %>
			<%= f.action :cancel, as: :link, label: "Cancel", button_html: { class: "pull-right" } %>
			<%= f.action :submit, as: :button, button_html: {class: "btn btn-primary pull-right"} %>
		<% end %>
	<% end %>

</div>

app/views/accounts/edit.WRONG.html.erb
<% provide(:title, "Edit account") %>
<h1>Edit account</h1>

<div class="container">

	<%= semantic_form_for @account, html: { class: 'span9 offset1', multipart: true } do |f| %>
		<%= f.inputs name: "Properties", id: "basic" do %>
			<%= f.inputs :name, class: "span6" %>
			<%= f.inputs :tag, 	class: "span2" %>

		  <div class="span8">
		    <% if @account.people.any? %>
		      People (<%= @account.people.count %>)
		      <ol class="people">
		        <%= render partial: 'person', collection: @account.people.order(:sort_order) %>
		      </ol>
		    <% end %>
		  </div>

			<%= f.inputs name: "Address", id: "address", class: "control-group controls row-fluid" do %>
				<%= render 'address_fields', f: f %>
			<% end %>

		<% end %>


		<%= f.actions class: "control-group controls row-fluid" do %>
			<%= f.action :cancel, as: :link, label: "Cancel", button_html: { class: "pull-right" } %>
			<%= f.action :submit, as: :button, button_html: {class: "btn btn-primary pull-right"} %>
		<% end %>
	<% end %>

</div>

app/views/accounts/edit.html.erb
<% provide(:title, "Edit account") %>
<h1>Edit account</h1>

<div class="container">

	<%= semantic_form_for @account, html: { class: 'span9 offset1', multipart: true } do |f| %>
		<%= f.inputs name: "Basic properties", id: "basic" do %>
			<%= f.inputs :name, class: "span6" %>
			<%= f.inputs :tag, 	class: "span2" %>

			<%= f.inputs name: "Address", id: "address", class: "control-group controls row-fluid" do %>
				<%= f.semantic_fields_for :address do |address| %>
					<%= address.inputs :label, 		class: "span6 row" %>
					<%= address.inputs :street1, 	class: "span6 row" %>
					<%= address.inputs :street2, 	class: "span2 row"%>
					<%= address.inputs :city, 		class: "span4 row"%>
					<%= address.inputs :state, 		class: "span2 row"%>
					<%= address.inputs :zip, 			class: "span2 row"%>
				<% end %>
			<% end %>

		<% end %>

		<%= f.inputs name: "Yizkors", id: "yizkors", class: "form-group" do %>
			<%= f.semantic_fields_for :yizkors, @account.yizkors.order(:sort_order, :id), 
																									class: "control-group" do |person| %>
				<%= render 'person_fields', f: person %>				
			<% end %>
	    	<div class='links'>
				<%= link_to_add_association "add yizkor", f, :people %>
	    	</div>
		<% end %>

		<%= f.actions class: "control-group controls row-fluid" do %>
			<%= f.action :cancel, as: :link, label: "Cancel", button_html: { class: "pull-right" } %>
			<%= f.action :submit, as: :button, button_html: {class: "btn btn-primary pull-right"} %>
		<% end %>
	<% end %>

</div>

app/views/accounts/index.html.erb
<% provide(:title, "Accounts") %>

<h1>
	Accounts
</h1>

<%= form_tag accounts_path, method: 'get' do %>
<div class="input-append">
  <%= text_field_tag :search, params[:search], class: "span6" %>
  <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
</div>
<% end %>


<ul id="accounts" class="accounts span7">
	<%= render @accounts %>
</ul>

app/views/accounts/show.html.erb
<% provide(:title, @account.name) %>

<h1>
  View account
</h1>

<ul id="accounts" class="accounts span7">
  <%= render @account %>
</ul>